"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.
"""

import os
from pathlib import Path

from dotenv import load_dotenv
import dj_database_url
from django.core.exceptions import ImproperlyConfigured

load_dotenv()

# ============================================================
# BASE
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# SECURITY
# ============================================================

DEBUG = os.getenv("DEBUG", "False").strip().lower() in {
    "true", "1", "yes"
}

SECRET_KEY = os.getenv("SECRET_KEY") or (
    "django-insecure-development-key-only" if DEBUG else ""
)

if not SECRET_KEY:
    raise ImproperlyConfigured(
        "Set SECRET_KEY in the environment when DEBUG is False."
    )

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "ALLOWED_HOSTS",
        "localhost,127.0.0.1,.onrender.com"
    ).split(",")
    if host.strip()
]

if DEBUG:
    ALLOWED_HOSTS = list(
        dict.fromkeys(
            ["localhost", "127.0.0.1", *ALLOWED_HOSTS]
        )
    )

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        "http://localhost:8000,https://localhost:8000"
    ).split(",")
    if origin.strip()
]

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = (
        "HTTP_X_FORWARDED_PROTO",
        "https",
    )

    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# ============================================================
# EMAIL
# ============================================================

EMAIL_HOST_USER = os.getenv(
    "EMAIL_HOST_USER",
    "tayadeyash999@gmail.com"
)

EMAIL_HOST_PASSWORD = (
    os.getenv("EMAIL_HOST_PASSWORD", "") or ""
).strip()

DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    EMAIL_HOST_USER
)

SERVER_EMAIL = DEFAULT_FROM_EMAIL

RECIPIENT_EMAIL = os.getenv(
    "RECIPIENT_EMAIL",
    EMAIL_HOST_USER
)

EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

EMAIL_BACKEND = (
    "django.core.mail.backends.console.EmailBackend"
    if (
        not EMAIL_HOST_PASSWORD
        or EMAIL_HOST_PASSWORD
        == "PASTE_YOUR_GMAIL_APP_PASSWORD_HERE"
    )
    else "django.core.mail.backends.smtp.EmailBackend"
)


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "portfolio",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# URL / TEMPLATES
# ============================================================

ROOT_URLCONF = "core.urls"

LOGIN_URL = "/admin-login/"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "portfolio.context_processors.dashboard_globals",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# ============================================================
# DATABASE
# ============================================================

DATABASES = {
    "default": dj_database_url.config(
        default="sqlite:///" + str(BASE_DIR / "db.sqlite3"),
        conn_max_age=600,
    )
}


# ============================================================
# SUPABASE STORAGE
# ============================================================
# Media files configuration
# Supabase Storage (S3-compatible)
# =========================
# SUPABASE S3 STORAGE
# =========================

AWS_ACCESS_KEY_ID = os.environ.get("SUPABASE_S3_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.environ.get("SUPABASE_S3_SECRET_ACCESS_KEY")

AWS_STORAGE_BUCKET_NAME = "portfolio-media"

AWS_S3_ENDPOINT_URL = os.environ.get("SUPABASE_S3_ENDPOINT")
AWS_S3_REGION_NAME = os.environ.get("SUPABASE_S3_REGION")

AWS_S3_ADDRESSING_STYLE = "path"

AWS_S3_CUSTOM_DOMAIN = (
    "qydubznugntpsbsegzkn.supabase.co"
    "/storage/v1/object/public/portfolio-media"
)

AWS_QUERYSTRING_AUTH = False

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static"
]

STATIC_ROOT = BASE_DIR / "staticfiles"


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME":
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator",
    },
    {
        "NAME":
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator",
    },
    {
        "NAME":
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator",
    },
    {
        "NAME":
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator",
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"