# Generated by Django 5.0 on 2026-10-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_achievement_date_alter_certificate_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='workshops/gallery/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.workshop')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]